service: api-tts
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  environment:
    REGION: 'us-east-1'
    BUCKET_NAME: 'sprint6-polly'	
    TABLE_NAME: 'sprint6teste'
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 's3:ListBucket'
            - 's3:PutObject'
          Resource: 'arn:aws:s3:::sprint6-polly'
        - Effect: Allow
          Action:
            - 'polly:SynthesizeSpeech'
          Resource: '*'
        - Effect: Allow
          Action:
            - 'dynamodb:BatchGetItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:BatchWriteItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
          Resource: 'arn:aws:dynamodb:us-east-1:033982107556:table/sprint6teste'

layers:
  polly:
    package: 
      artifact: layers/polly/polly.zip
  s3:
    package:
      artifact: layers/s3/s3.zip
  dynamo:
    package:
      artifact: layers/dynamo/dynamo.zip
functions:
  health:
    handler: handler.health
    events:
      - httpApi:
          path: /
          method: get
  v1Description:
    handler: handler.v1_description
    events:
      - httpApi:
          path: /v1
          method: get
  v2Description:
    handler: handler.v2_description
    events:
      - httpApi:
          path: /v2
          method: get
  v1_tts:
    handler: src.v1.v1_tts
    layers:
      - !Ref PollyLambdaLayer
      - !Ref S3LambdaLayer
    events:
      - httpApi:
          path: /v1/tts
          method: post
  v2_tts:
    handler: src.v2.v2_tts
    layers:
      - !Ref PollyLambdaLayer
      - !Ref S3LambdaLayer
      - !Ref DynamoLambdaLayer
    events:
      - httpApi:
          path: /v2/tts
          method: post
  v3_tts:
    handler: src.v3.v3_tts
    layers:
      - !Ref PollyLambdaLayer
      - !Ref S3LambdaLayer
      - !Ref DynamoLambdaLayer
    events:
      - httpApi:
          path: /v3/tts
          method: post

